#################################################################
  - id: livingroom_tv_atv
    alias: Livingroom TV and ATV
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: media_player.livingroom_tv
        to: 'on'
    action: 
      - service: media_player.turn_on
        data:
          entity_id: media_player.livingroom_atv

################################################################
